#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
# - {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Castle On The Hill',   url: 'castle'} {name: 'Chess Pieces',   url: 'chess'}
- {name: 'GE Turret', url: 'turret'}
- {name: 'Mars Rover Illustration',  url: 'rover'}
- {name: 'Motion Graphics Loops',  url: 'loops'}
- {name: 'Paper Airplanes Illustration',   url: 'paper-planes'}
- {name: 'Fake Portal Teaser',   url: 'portal'}
- {name: 'Solar Cooler Model', url: 'cooler'}
- {name: 'Space Concept Art',  url: 'space-concepts'}
- {name: 'Spaceship Sketches',  url: 'space-sketches'}
- {name: 'Small Home Render',   url: 'house-tour'}
- {name: 'Plant Post',   url: 'plant-post'}
- {name: 'Anti-Nuke Posters', url: 'nukes-bad'}
- {name: 'Bose Headphones Commercials',  url: 'headphones'}
- {name: 'Logo Design Mockups',  url: 'logos'}
- {name: 'Playing Card Designs',   url: 'playing-cards'}
- {name: 'Anti-Prison Poster',   url: 'prison-bad'}
- {name: 'Theatre-Poster-Mockup', url: 'theatre-poster'}
- {name: 'Themis Files Trilogy Cover Designs',  url: 'book-covers'}
- {name: 'Truman State Postcards',  url: 'postcards'}
- {name: 'Tile Spacer Photos',   url: 'tile-spacers'}
- {name: 'Gauze Photos',   url: 'gauze'}
- {name: 'Lifeblood', url: 'lifeblood'}
- {name: 'Lucid Escape',  url: 'lucid-escape'}
- {name: 'Market Worship',  url: 'market-worship'}
- {name: 'Level 1', url: 'level-1'}
- {name: 'Floating Cat',  url: 'floating-cat'}
- {name: 'Orange Study',  url: 'oil-orange'}
- {name: 'Linocuts',   url: 'linocuts'}
- {name: 'Basic Living', url: 'basic-living'}
- {name: 'California Home Drafting',  url: 'california'}
- {name: 'Nebraska Home Drafting',  url: 'nebraska'}
- {name: 'Lily Home Drafting',  url: 'lily'}



#-------------------------------
# Contact Section

social:
# - {icon: 'twitter',   link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/scafewesley'}
# - {icon: 'github',    link: 'https://github.com/brickchucker'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/wesley-scafe-417626126/'}
- {icon: 'envelope',  link: 'mailto:mailto:yettobecreatedemail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Wesley Scafe 3D artist and drafter portfolio powered by Jekyll and GitHub Pages'
  rel-author: 'https://www.instagram.com/scafewesley'
  rel-publisher: 'https://www.instagram.com/scafewesley'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
